# Generated by Django 5.2 on 2026-06-29 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hierarchy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('subject_type', models.CharField(max_length=100)),
                ('trigger_event', models.CharField(blank=True, default='', max_length=80)),
                ('steps', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'workflows_definition',
                'ordering': ['code', '-version'],
                'indexes': [models.Index(fields=['subject_type', 'is_current'], name='wf_def_subj_cur_idx'), models.Index(fields=['code', 'is_current'], name='wf_def_code_cur_idx')],
                'constraints': [models.UniqueConstraint(fields=('code', 'version'), name='wf_def_code_ver_uniq')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('subject_type', models.CharField(db_index=True, max_length=100)),
                ('subject_id', models.BigIntegerField()),
                ('current_step', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated'), ('auto_approved', 'Auto-approved'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('sla_due_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('anchor_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_instances', to='hierarchy.node')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='workflows.workflowdefinition')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflows_instance',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=150)),
                ('approval_mode', models.CharField(default='single', max_length=10)),
                ('condition', models.JSONField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('assignee_role_code', models.CharField(blank=True, default='', max_length=80)),
                ('assignee_user_ids', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('skipped', 'Skipped'), ('escalated', 'Escalated'), ('auto_approved', 'Auto-approved')], db_index=True, default='pending', max_length=15)),
                ('sla_due_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assignee_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hierarchy.node')),
                ('assignee_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflows.workflowinstance')),
            ],
            options={
                'db_table': 'workflows_step',
                'ordering': ['workflow_id', 'order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('step_order', models.PositiveIntegerField(default=0)),
                ('action', models.CharField(choices=[('initiate', 'Initiate'), ('approve', 'Approve'), ('reject', 'Reject'), ('escalate', 'Escalate'), ('comment', 'Comment'), ('delegate', 'Delegate'), ('reassign', 'Reassign'), ('auto_approve', 'Auto-approve')], max_length=15)),
                ('comments', models.TextField(blank=True, default='')),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='workflows.workflowinstance')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='workflows.workflowstep')),
            ],
            options={
                'db_table': 'workflows_action',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('scope', models.CharField(blank=True, default='all', max_length=80)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True, default='')),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_received', to=settings.AUTH_USER_MODEL)),
                ('delegator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflows_delegation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['delegate', 'start_date', 'end_date'], name='wf_deleg_delegate_idx'), models.Index(fields=['delegator', 'start_date', 'end_date'], name='wf_deleg_delegator_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['status', 'sla_due_at'], name='wf_inst_status_sla_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['subject_type', 'subject_id'], name='wf_inst_subject_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowstep',
            index=models.Index(fields=['status'], name='wf_step_status_idx'),
        ),
    ]
