# Generated by Django 5.2 on 2026-06-29 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hierarchy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('role_in_scope', models.CharField(choices=[('owner', 'Owner'), ('stand_in', 'Stand-in'), ('supervisor', 'Supervisor')], default='owner', max_length=20)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='hierarchy.node')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='hierarchy.geographynode')),
            ],
            options={
                'db_table': 'assignments_assignment',
                'indexes': [models.Index(fields=['scope', 'role_in_scope', 'effective_from'], name='assign_scope_role_from_idx'), models.Index(fields=['assignee', 'effective_from'], name='assign_assignee_from_idx')],
            },
        ),
    ]
