# Generated by Django 5.2 on 2026-07-14 09:37

from django.db import migrations, models


def _drop_quarterly_periods(apps, schema_editor):
    """Targets are set monthly — quarters are gone. Reparent each quarter's months to the
    quarter's parent (the annual container), fix their path/depth, then delete the quarter.
    Quarterly allocations cascade away (targets were never legitimately set on quarters)."""
    TargetPeriod = apps.get_model('targets', 'TargetPeriod')
    for quarter in TargetPeriod.objects.filter(period_type='quarterly'):
        parent = quarter.parent
        for child in TargetPeriod.objects.filter(parent=quarter):
            child.parent = parent
            if parent is not None:
                child.path = parent.path + child.code + '/'
                child.depth = parent.depth + 1
            else:
                child.path = f'/{child.code}/'
                child.depth = 0
            child.save(update_fields=['parent', 'path', 'depth'])
        quarter.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plankpi',
            name='curve',
        ),
        migrations.AlterField(
            model_name='planrun',
            name='kind',
            field=models.CharField(choices=[('baseline', 'Baseline'), ('top_down', 'Top number'), ('spatial', 'Spatial split'), ('product', 'Product split'), ('realign', 'Realignment re-split')], max_length=20),
        ),
        migrations.AlterField(
            model_name='targetperiod',
            name='period_type',
            field=models.CharField(choices=[('annual', 'Annual'), ('monthly', 'Monthly'), ('scheme', 'Scheme'), ('custom', 'Custom')], default='monthly', max_length=20),
        ),
        migrations.RunPython(_drop_quarterly_periods, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='SeasonalityCurve',
        ),
    ]
