# Generated by Django 5.2 on 2026-07-16 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_remove_plankpi_curve_alter_planrun_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetrevision',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='side_effects', to='targets.targetrevision'),
        ),
    ]
