# Generated by Django 5.2 on 2026-06-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('category', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('sub_category', models.CharField(blank=True, default='', max_length=150)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_focus', models.BooleanField(db_index=True, default=False)),
                ('is_npi', models.BooleanField(db_index=True, default=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'master_data_sku',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['brand', 'category'], name='master_data_brand_a61193_idx')],
                'constraints': [models.UniqueConstraint(fields=('code',), name='sku_code_uniq')],
            },
        ),
        migrations.CreateModel(
            name='UOMConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sku_code', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('from_uom', models.CharField(max_length=20)),
                ('to_uom', models.CharField(max_length=20)),
                ('factor', models.DecimalField(decimal_places=6, default=1, max_digits=15)),
            ],
            options={
                'db_table': 'master_data_uomconversion',
                'ordering': ['sku_code', 'from_uom'],
                'constraints': [models.UniqueConstraint(fields=('sku_code', 'from_uom'), name='uom_conv_sku_from_uniq')],
            },
        ),
        migrations.CreateModel(
            name='SKUGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('filter_type', models.CharField(choices=[('explicit', 'Explicit (fixed list)'), ('rule', 'Rule (dynamic filter)')], default='explicit', max_length=20)),
                ('filter_rules', models.JSONField(blank=True, default=dict)),
                ('skus', models.ManyToManyField(blank=True, related_name='groups', to='master_data.sku')),
            ],
            options={
                'db_table': 'master_data_skugroup',
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(fields=('code',), name='skugroup_code_uniq')],
            },
        ),
    ]
