# Generated by Django 5.2 on 2026-06-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditChainHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_hash', models.CharField(blank=True, default='', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'audit_chainhead',
            },
        ),
        migrations.CreateModel(
            name='RetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('log_type', models.CharField(choices=[('audit', 'Audit Log'), ('access', 'Access Log'), ('computation', 'Computation Log'), ('report_artifact', 'Report Artifact')], max_length=30, unique=True)),
                ('retain_days', models.PositiveIntegerField()),
                ('archive_strategy', models.CharField(default='delete', max_length=20)),
            ],
            options={
                'db_table': 'audit_retentionpolicy',
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True, null=True)),
                ('resource', models.CharField(db_index=True, max_length=50)),
                ('object_id', models.BigIntegerField(null=True)),
                ('subject_entity_id', models.BigIntegerField(db_index=True, null=True)),
                ('action', models.CharField(default='view', max_length=20)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.CharField(blank=True, max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'audit_accesslog',
                'indexes': [models.Index(fields=['resource', 'timestamp'], name='audit_access_res_ts_idx'), models.Index(fields=['subject_entity_id', 'timestamp'], name='audit_access_subj_ts_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=50)),
                ('entity_type', models.CharField(db_index=True, max_length=200)),
                ('entity_id', models.BigIntegerField(db_index=True)),
                ('user_id', models.BigIntegerField(db_index=True, null=True)),
                ('changes', models.JSONField(default=dict)),
                ('prev_hash', models.CharField(blank=True, default='', max_length=64)),
                ('row_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_auditlog',
                'indexes': [models.Index(fields=['entity_type', 'entity_id', 'timestamp'], name='audit_log_entity_ts_idx'), models.Index(fields=['user_id', 'timestamp'], name='audit_log_user_ts_idx')],
            },
        ),
        migrations.CreateModel(
            name='ComputationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computation_type', models.CharField(db_index=True, max_length=50)),
                ('entity_id', models.BigIntegerField(db_index=True)),
                ('period_id', models.BigIntegerField(null=True)),
                ('triggered_by_id', models.BigIntegerField(null=True)),
                ('config_snapshot', models.JSONField(default=dict)),
                ('result_snapshot', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_computationlog',
                'indexes': [models.Index(fields=['entity_id', 'computation_type'], name='audit_comp_entity_type_idx'), models.Index(fields=['timestamp'], name='audit_comp_ts_idx')],
            },
        ),
    ]
