# Generated by Django 5.2 on 2026-06-29 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hierarchy', '0001_initial'),
        ('kpi_engine', '0001_initial'),
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('target_value', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('achieved_value', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('gross_value', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('returns_value', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('achievement_pct', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('gap_to_target', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('daily_run_rate', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('projected_value', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('projected_pct', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('required_run_rate', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('working_days_elapsed', models.PositiveIntegerField(default=0)),
                ('working_days_total', models.PositiveIntegerField(default=0)),
                ('ly_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('growth_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_provisional', models.BooleanField(default=True)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('computation_id', models.BigIntegerField(blank=True, null=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='hierarchy.channel')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='hierarchy.node')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achievements', to='kpi_engine.kpidefinition')),
                ('target_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='targets.targetperiod')),
            ],
            options={
                'db_table': 'achievements_achievement',
                'ordering': ['target_period', 'kpi', 'entity'],
            },
        ),
        migrations.CreateModel(
            name='AchievementSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('achieved_value', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('achievement_pct', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('projected_pct', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='achievements.achievement')),
            ],
            options={
                'db_table': 'achievements_snapshot',
                'ordering': ['snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('metric', models.CharField(choices=[('achievement_pct', 'Achievement %'), ('projected_pct', 'Projected month-end %'), ('gap_to_target', 'Gap to target'), ('required_run_rate', 'Required run rate'), ('no_sale_days', 'Days since last sale'), ('growth_pct', 'Growth vs last year')], max_length=30)),
                ('comparator', models.CharField(choices=[('lt', '<'), ('lte', 'â‰¤'), ('gt', '>'), ('gte', 'â‰¥'), ('eq', '=')], default='lt', max_length=3)),
                ('threshold', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('scope_entity_types', models.JSONField(blank=True, default=list)),
                ('scope_channels', models.JSONField(blank=True, default=list)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('recipient_role', models.CharField(blank=True, default='', max_length=50)),
                ('message_template', models.CharField(blank=True, default='{entity}: {metric} is {value}', max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('kpi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_rules', to='kpi_engine.kpidefinition')),
            ],
            options={
                'db_table': 'achievements_alertrule',
                'ordering': ['code', '-version'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metric_value', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=15)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('computation_id', models.BigIntegerField(blank=True, null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='hierarchy.node')),
                ('kpi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='kpi_engine.kpidefinition')),
                ('target_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='targets.targetperiod')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='achievements.alertrule')),
            ],
            options={
                'db_table': 'achievements_alert',
                'ordering': ['-computed_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['entity', 'target_period'], name='achv_entity_period_idx'),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['target_period', 'kpi'], name='achv_period_kpi_idx'),
        ),
        migrations.AddConstraint(
            model_name='achievement',
            constraint=models.UniqueConstraint(condition=models.Q(('channel__isnull', False)), fields=('target_period', 'kpi', 'entity', 'channel'), name='achievement_dim_uniq'),
        ),
        migrations.AddConstraint(
            model_name='achievement',
            constraint=models.UniqueConstraint(condition=models.Q(('channel__isnull', True)), fields=('target_period', 'kpi', 'entity'), name='achievement_dim_nochan_uniq'),
        ),
        migrations.AddConstraint(
            model_name='achievementsnapshot',
            constraint=models.UniqueConstraint(fields=('achievement', 'snapshot_date'), name='achv_snapshot_day_uniq'),
        ),
        migrations.AddConstraint(
            model_name='alertrule',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='achv_alertrule_code_ver_uniq'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['entity', 'target_period', 'status'], name='achv_alert_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.UniqueConstraint(condition=models.Q(('kpi__isnull', False)), fields=('rule', 'entity', 'target_period', 'kpi'), name='achv_alert_dim_uniq'),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.UniqueConstraint(condition=models.Q(('kpi__isnull', True)), fields=('rule', 'entity', 'target_period'), name='achv_alert_dim_nokpi_uniq'),
        ),
    ]
