# Generated by Django 5.2 on 2026-07-08 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
        ('hierarchy', '0003_drop_node_geography_fk'),
        ('kpi_engine', '0002_externalmetric_kpidefinition_external_config_and_more'),
        ('master_data', '0001_initial'),
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerritoryAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('target_value', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('achieved_value', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('achievement_pct', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('gap_to_target', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('computation_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'achievements_territory',
                'ordering': ['target_period', 'kpi', 'node'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='achievement',
            name='achievement_dim_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='achievement',
            name='achievement_dim_nochan_uniq',
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='comparator',
            field=models.CharField(choices=[('lt', '<'), ('lte', '≤'), ('gt', '>'), ('gte', '≥'), ('eq', '=')], default='lt', max_length=3),
        ),
        migrations.AddConstraint(
            model_name='achievement',
            constraint=models.UniqueConstraint(fields=('target_period', 'kpi', 'entity', 'channel'), name='achievement_dim_uniq', nulls_distinct=False),
        ),
        migrations.AddField(
            model_name='territoryachievement',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='territory_achievements', to='hierarchy.channel'),
        ),
        migrations.AddField(
            model_name='territoryachievement',
            name='kpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='territory_achievements', to='kpi_engine.kpidefinition'),
        ),
        migrations.AddField(
            model_name='territoryachievement',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territory_achievements', to='hierarchy.geographynode'),
        ),
        migrations.AddField(
            model_name='territoryachievement',
            name='sku_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='territory_achievements', to='master_data.skugroup'),
        ),
        migrations.AddField(
            model_name='territoryachievement',
            name='target_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territory_achievements', to='targets.targetperiod'),
        ),
        migrations.AddIndex(
            model_name='territoryachievement',
            index=models.Index(fields=['target_period', 'kpi'], name='territory_achv_period_kpi_idx'),
        ),
        migrations.AddIndex(
            model_name='territoryachievement',
            index=models.Index(fields=['node', 'target_period'], name='territory_achv_node_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='territoryachievement',
            constraint=models.UniqueConstraint(fields=('target_period', 'kpi', 'node', 'channel', 'sku_group'), name='territory_achv_dim_uniq', nulls_distinct=False),
        ),
    ]
