# Generated by Django 5.2 on 2026-06-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('code', models.CharField(max_length=60, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_enabled', models.BooleanField(default=False)),
                ('scope', models.CharField(choices=[('global', 'Global'), ('role', 'Role'), ('entity_type', 'Node Type')], default='global', max_length=20)),
                ('scope_value', models.CharField(blank=True, default='', max_length=60)),
            ],
            options={
                'db_table': 'admin_featureflag',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('key', models.CharField(max_length=80, unique=True)),
                ('category', models.CharField(choices=[('financial', 'Financial'), ('tds', 'TDS'), ('locale', 'Locale'), ('branding', 'Branding'), ('security', 'Security'), ('feature', 'Feature')], db_index=True, max_length=20)),
                ('value', models.JSONField()),
                ('value_type', models.CharField(default='string', max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_sensitive', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'admin_systemsetting',
                'ordering': ['category', 'key'],
            },
        ),
    ]
