# Generated by Django 5.2 on 2026-06-29 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('job_type', models.CharField(choices=[('entity_import', 'Node Import'), ('user_import', 'User Import'), ('entity_bulk_move', 'Node Bulk Move'), ('entity_bulk_deactivate', 'Node Bulk Deactivate'), ('user_bulk_roles', 'User Bulk Role Assignment'), ('entity_export', 'Node Export'), ('sku_import', 'SKU Import'), ('transaction_import', 'Transaction Import'), ('target_disaggregation', 'Target Disaggregation'), ('target_phasing', 'Target Phasing'), ('target_import', 'Target Import'), ('achievement_compute', 'Achievement Computation'), ('payout_compute', 'Payout Computation'), ('loyalty_compute', 'Loyalty Earning Computation')], max_length=40)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('validating', 'Validating'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial')], db_index=True, default='queued', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job_type', 'status'], name='jobs_bulkjo_job_typ_e514d3_idx'), models.Index(fields=['created_by', '-created_at'], name='jobs_bulkjo_created_2f5fad_idx')],
            },
        ),
    ]
