# Generated by Django 5.2 on 2026-07-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_bulkjob_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkjob',
            name='job_type',
            field=models.CharField(choices=[('entity_import', 'Node Import'), ('user_import', 'User Import'), ('entity_bulk_move', 'Node Bulk Move'), ('entity_bulk_deactivate', 'Node Bulk Deactivate'), ('user_bulk_roles', 'User Bulk Role Assignment'), ('entity_export', 'Node Export'), ('sku_import', 'SKU Import'), ('transaction_import', 'Transaction Import'), ('metric_import', 'External Metric Value Import'), ('target_disaggregation', 'Target Disaggregation'), ('target_phasing', 'Target Phasing'), ('target_import', 'Target Import'), ('achievement_compute', 'Achievement Computation'), ('payout_compute', 'Payout Computation')], max_length=40),
        ),
    ]
