# Generated by Django 5.2 on 2026-07-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_bulkjob_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkjob',
            name='job_type',
            field=models.CharField(choices=[('entity_import', 'Node Import'), ('user_import', 'User Import'), ('entity_bulk_move', 'Node Bulk Move'), ('entity_bulk_deactivate', 'Node Bulk Deactivate'), ('user_bulk_roles', 'User Bulk Role Assignment'), ('entity_export', 'Node Export'), ('sku_import', 'SKU Import'), ('geography_import', 'Territory Import'), ('transaction_import', 'Transaction Import'), ('metric_import', 'External Metric Value Import'), ('target_disaggregation', 'Target Disaggregation'), ('target_phasing', 'Target Phasing'), ('target_import', 'Target Import'), ('plan_run', 'Target Plan Run'), ('achievement_compute', 'Achievement Computation'), ('payout_compute', 'Payout Computation'), ('cycle_finalize', 'Payout Cycle Finalize'), ('cycle_compute', 'Payout Cycle Compute')], max_length=40),
        ),
    ]
