# Generated by Django 5.2 on 2026-06-29 06:22

import apps.reports.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=60, unique=True)),
                ('category', models.CharField(choices=[('sales', 'Sales & Distribution'), ('coverage', 'Coverage & Productivity'), ('targets', 'Targets & Achievement'), ('incentive', 'Incentive & Payout'), ('compliance', 'Compliance'), ('loyalty', 'Loyalty & Channel Partner'), ('master', 'Master & Audit')], db_index=True, max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('param_schema', models.JSONField(default=list)),
                ('default_formats', models.JSONField(default=list)),
                ('required_permission', models.CharField(max_length=50)),
                ('is_confidential', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'reports_definition',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=120)),
                ('parameters', models.JSONField(default=dict)),
                ('format', models.CharField(choices=[('xlsx', 'Excel'), ('pdf', 'PDF'), ('csv', 'CSV')], default='xlsx', max_length=10)),
                ('cron_minute', models.CharField(default='0', max_length=60)),
                ('cron_hour', models.CharField(default='6', max_length=60)),
                ('cron_day_of_week', models.CharField(default='*', max_length=60)),
                ('cron_day_of_month', models.CharField(default='*', max_length=60)),
                ('cron_month_of_year', models.CharField(default='*', max_length=60)),
                ('recipients', models.JSONField(default=dict)),
                ('delivery', models.CharField(choices=[('in_app', 'In-app'), ('email', 'Email'), ('both', 'Both')], default='both', max_length=10)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('periodic_task_id', models.BigIntegerField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='reports.reportdefinition')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports_schedule',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('parameters', models.JSONField(default=dict)),
                ('scope_snapshot', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('format', models.CharField(choices=[('xlsx', 'Excel'), ('pdf', 'PDF'), ('csv', 'CSV')], default='xlsx', max_length=10)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('file', models.FileField(blank=True, max_length=500, null=True, upload_to=apps.reports.models.report_upload_path)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('computation_refs', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='reports.reportdefinition')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports_execution',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['requested_by', '-created_at'], name='reports_exe_request_2bd2f5_idx'), models.Index(fields=['definition', 'status'], name='reports_exe_definit_1076fb_idx')],
            },
        ),
    ]
