# Generated by Django 5.2 on 2026-07-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_deliverytarget_reportdefinition_is_dataset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdefinition',
            name='category',
            field=models.CharField(choices=[('sales', 'Sales & Distribution'), ('coverage', 'Coverage & Productivity'), ('targets', 'Targets & Achievement'), ('incentive', 'Incentive & Payout'), ('compliance', 'Compliance'), ('master', 'Master & Audit')], db_index=True, max_length=20),
        ),
    ]
