# Generated by Django 5.2 on 2026-06-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KpiTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('unit', models.CharField(blank=True, default='', max_length=30)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2)),
                ('kpi_type', models.CharField(choices=[('value', 'Value (sum)'), ('count', 'Count'), ('count_distinct', 'Count distinct'), ('ratio', 'Ratio'), ('growth', 'Growth'), ('composite', 'Composite'), ('boolean', 'Boolean / threshold')], default='value', max_length=20)),
                ('measure_config', models.JSONField(blank=True, default=dict)),
                ('ratio_config', models.JSONField(blank=True, default=dict)),
                ('growth_config', models.JSONField(blank=True, default=dict)),
                ('composite_config', models.JSONField(blank=True, default=dict)),
                ('boolean_config', models.JSONField(blank=True, default=dict)),
                ('sku_filter', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'kpi_engine_kpitemplate',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KPIDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('unit', models.CharField(blank=True, default='', max_length=30)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2)),
                ('kpi_type', models.CharField(choices=[('value', 'Value (sum)'), ('count', 'Count'), ('count_distinct', 'Count distinct'), ('ratio', 'Ratio'), ('growth', 'Growth'), ('composite', 'Composite'), ('boolean', 'Boolean / threshold')], default='value', max_length=20)),
                ('measure_config', models.JSONField(blank=True, default=dict)),
                ('ratio_config', models.JSONField(blank=True, default=dict)),
                ('growth_config', models.JSONField(blank=True, default=dict)),
                ('composite_config', models.JSONField(blank=True, default=dict)),
                ('boolean_config', models.JSONField(blank=True, default=dict)),
                ('applicable_entity_types', models.JSONField(blank=True, default=list)),
                ('channel_filter', models.JSONField(blank=True, default=list)),
                ('sku_filter', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'kpi_engine_kpidefinition',
                'ordering': ['code', '-version'],
                'indexes': [models.Index(fields=['is_current', 'kpi_type'], name='kpi_def_cur_type_idx'), models.Index(fields=['category', 'is_current'], name='kpi_def_cat_cur_idx')],
                'constraints': [models.UniqueConstraint(fields=('code', 'version'), name='kpi_definition_code_ver_uniq')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('attributed_node_id', models.BigIntegerField(db_index=True)),
                ('outlet_code', models.CharField(blank=True, default='', max_length=50)),
                ('bill_ref', models.CharField(blank=True, default='', max_length=80)),
                ('sku_code', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('channel_code', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('transaction_date', models.DateField(db_index=True)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale'), ('return', 'Return'), ('credit_note', 'Credit note')], default='sale', max_length=20)),
                ('transaction_level', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('tertiary', 'Tertiary')], db_index=True, default='secondary', max_length=20)),
                ('source', models.CharField(blank=True, default='', max_length=30)),
                ('external_ref', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('uom', models.CharField(blank=True, default='', max_length=20)),
                ('base_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
            ],
            options={
                'db_table': 'kpi_engine_transaction',
                'ordering': ['-transaction_date', '-id'],
                'indexes': [models.Index(fields=['attributed_node_id', 'transaction_date'], name='kpi_txn_node_date_idx'), models.Index(fields=['channel_code', 'transaction_date'], name='kpi_txn_chan_date_idx'), models.Index(fields=['transaction_date', 'transaction_level'], name='kpi_txn_date_lvl_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_ref', ''), _negated=True), fields=('source', 'external_ref'), name='kpi_txn_source_ref_uniq')],
            },
        ),
    ]
