# Generated by Django 5.2 on 2026-07-02 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0001_initial'),
        ('kpi_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('unit', models.CharField(blank=True, default='', max_length=30)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2)),
                ('granularity', models.CharField(choices=[('entity', 'Person (organisation entity)'), ('geography_node', 'Territory (geography node)')], default='geography_node', max_length=20)),
                ('period_grain', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly')], default='monthly', max_length=10)),
                ('default_aggregation', models.CharField(choices=[('sum', 'Sum'), ('avg', 'Average'), ('latest', 'Latest'), ('max', 'Max')], default='sum', max_length=10)),
            ],
            options={
                'db_table': 'kpi_engine_externalmetric',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='kpidefinition',
            name='external_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='kpitemplate',
            name='external_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='kpidefinition',
            name='kpi_type',
            field=models.CharField(choices=[('value', 'Value (sum)'), ('count', 'Count'), ('count_distinct', 'Count distinct'), ('ratio', 'Ratio'), ('growth', 'Growth'), ('composite', 'Composite'), ('boolean', 'Boolean / threshold'), ('external', 'External metric')], default='value', max_length=20),
        ),
        migrations.AlterField(
            model_name='kpitemplate',
            name='kpi_type',
            field=models.CharField(choices=[('value', 'Value (sum)'), ('count', 'Count'), ('count_distinct', 'Count distinct'), ('ratio', 'Ratio'), ('growth', 'Growth'), ('composite', 'Composite'), ('boolean', 'Boolean / threshold'), ('external', 'External metric')], default='value', max_length=20),
        ),
        migrations.CreateModel(
            name='ExternalMetricValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('node_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('measured_on', models.DateField(db_index=True)),
                ('value', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('source', models.CharField(blank=True, default='', max_length=30)),
                ('external_ref', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_metric_values', to='hierarchy.node')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='kpi_engine.externalmetric')),
            ],
            options={
                'db_table': 'kpi_engine_externalmetricvalue',
                'ordering': ['-measured_on', '-id'],
                'indexes': [models.Index(fields=['metric', 'measured_on'], name='kpi_emv_metric_date_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_ref', ''), _negated=True), fields=('source', 'external_ref'), name='kpi_emv_source_ref_uniq'), models.UniqueConstraint(condition=models.Q(('entity__isnull', False)), fields=('metric', 'entity', 'measured_on'), name='kpi_emv_metric_entity_day_uniq'), models.UniqueConstraint(condition=models.Q(('node_id__isnull', False)), fields=('metric', 'node_id', 'measured_on'), name='kpi_emv_metric_node_day_uniq')],
            },
        ),
        migrations.CreateModel(
            name='IntegrationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('batch_kind', models.CharField(choices=[('transactions', 'Transactions'), ('metric_values', 'Metric values')], max_length=20)),
                ('source', models.CharField(max_length=30)),
                ('client_batch_ref', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('received_count', models.PositiveIntegerField(default=0)),
                ('accepted_count', models.PositiveIntegerField(default=0)),
                ('rejected_count', models.PositiveIntegerField(default=0)),
                ('row_errors', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('partial', 'Partial'), ('rejected', 'Rejected')], max_length=10)),
                ('pushed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kpi_engine_integrationbatch',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('client_batch_ref', ''), _negated=True), fields=('batch_kind', 'source', 'client_batch_ref'), name='kpi_batch_kind_src_ref_uniq')],
            },
        ),
    ]
