# Generated by Django 5.2 on 2026-06-29 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'hierarchy_channel',
            },
        ),
        migrations.CreateModel(
            name='GeographyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('levels', models.JSONField(default=list)),
                ('attribute_schema', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'hierarchy_geographytype',
            },
        ),
        migrations.CreateModel(
            name='GeographyNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('path', models.CharField(blank=True, db_index=True, default='', max_length=1000)),
                ('depth', models.PositiveIntegerField(default=0)),
                ('attributes', models.JSONField(default=dict)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='hierarchy.geographynode')),
                ('geography_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='hierarchy.geographytype')),
            ],
            options={
                'db_table': 'hierarchy_geographynode',
            },
        ),
        migrations.CreateModel(
            name='NodeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('level_order', models.PositiveIntegerField()),
                ('allowed_parent_types', models.JSONField(default=list)),
                ('allowed_child_types', models.JSONField(default=list)),
                ('attribute_schema', models.JSONField(default=list)),
                ('is_loginable', models.BooleanField(default=False)),
                ('incentive_eligible', models.BooleanField(default=False)),
                ('loyalty_eligible', models.BooleanField(default=False)),
                ('is_leaf', models.BooleanField(default=False)),
                ('is_root_type', models.BooleanField(default=False)),
                ('display_config', models.JSONField(default=dict)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node_types', to='hierarchy.channel')),
                ('default_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node_types', to='accounts.role')),
            ],
            options={
                'db_table': 'hierarchy_nodetype',
                'ordering': ['level_order'],
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('attributes', models.JSONField(default=dict)),
                ('path', models.CharField(blank=True, db_index=True, default='', max_length=1000)),
                ('depth', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=20)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='hierarchy.channel')),
                ('geography_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='hierarchy.geographynode')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='hierarchy.node')),
                ('entity_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='hierarchy.nodetype')),
            ],
            options={
                'db_table': 'hierarchy_node',
            },
        ),
        migrations.CreateModel(
            name='RelationshipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('allows_multiple', models.BooleanField(default=True)),
                ('from_entity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_relationship_types', to='hierarchy.nodetype')),
                ('to_entity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_relationship_types', to='hierarchy.nodetype')),
            ],
            options={
                'db_table': 'hierarchy_relationshiptype',
            },
        ),
        migrations.CreateModel(
            name='NodeRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('from_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='hierarchy.node')),
                ('to_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='hierarchy.node')),
                ('relationship_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='hierarchy.relationshiptype')),
            ],
            options={
                'db_table': 'hierarchy_noderelationship',
            },
        ),
        migrations.AddConstraint(
            model_name='nodetype',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='hierarchy_nodetype_code_ver_uniq'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['entity_type', 'is_current'], name='hier_node_type_cur_idx'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['parent', 'is_current'], name='hier_node_par_cur_idx'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['status'], name='hier_node_status_idx'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['channel', 'entity_type'], name='hier_node_chan_type_idx'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['path', 'is_current', 'is_active'], name='hier_node_path_cur_act_idx'),
        ),
        migrations.AddConstraint(
            model_name='node',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='hierarchy_node_code_ver_uniq'),
        ),
        migrations.AddIndex(
            model_name='noderelationship',
            index=models.Index(fields=['from_entity', 'relationship_type'], name='hierarchy_nr_from_type_idx'),
        ),
        migrations.AddIndex(
            model_name='noderelationship',
            index=models.Index(fields=['to_entity', 'relationship_type'], name='hierarchy_nr_to_type_idx'),
        ),
    ]
