# Generated by Django 5.2 on 2026-07-03 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodetype',
            name='loyalty_eligible',
        ),
    ]
