# Generated by Django 5.2 on 2026-07-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0003_drop_node_geography_fk'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='geographynode',
            index=models.Index(fields=['code'], name='hier_geo_code_idx'),
        ),
        migrations.AddIndex(
            model_name='geographynode',
            index=models.Index(fields=['geography_type', 'level'], name='hier_geo_type_lvl_idx'),
        ),
        migrations.AddIndex(
            model_name='geographynode',
            index=models.Index(fields=['parent', 'is_active'], name='hier_geo_par_act_idx'),
        ),
        migrations.AddIndex(
            model_name='geographynode',
            index=models.Index(fields=['geography_type', 'parent', 'is_active'], name='hier_geo_type_par_idx'),
        ),
    ]
