# Generated by Django 5.2 on 2026-07-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0005_trgm_search_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['name'], name='hier_node_name_idx'),
        ),
    ]
