# Generated by Django 5.2 on 2026-07-02 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0001_initial'),
        ('kpi_engine', '0002_externalmetric_kpidefinition_external_config_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incentivescheme',
            name='gatekeeper_kpi',
        ),
        migrations.RemoveField(
            model_name='incentivescheme',
            name='gatekeeper_threshold_pct',
        ),
        migrations.AddField(
            model_name='payout',
            name='gate_results',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='SchemeGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('operator', models.CharField(choices=[('gte', '≥'), ('gt', '>')], default='gte', max_length=5)),
                ('threshold_pct', models.DecimalField(decimal_places=2, max_digits=8)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_schemes', to='kpi_engine.kpidefinition')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gates', to='incentives.incentivescheme')),
            ],
            options={
                'db_table': 'incentives_schemegate',
                'ordering': ['display_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('scheme', 'kpi'), name='inc_gate_scheme_kpi_uniq')],
            },
        ),
    ]
