# Generated by Django 5.2 on 2026-07-02 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0001_initial'),
        ('incentives', '0002_remove_incentivescheme_gatekeeper_kpi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceptioncategory',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exception_categories', to='hierarchy.channel'),
        ),
        migrations.AddField(
            model_name='exceptioncategory',
            name='duration_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payoutexception',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='incentives.payoutexception'),
        ),
        migrations.AddField(
            model_name='payoutexception',
            name='reference_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
