# Generated by Django 5.2 on 2026-07-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0003_exceptioncategory_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incentivescheme',
            name='payout_frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=10),
        ),
    ]
