# Generated by Django 5.2 on 2026-07-08 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0004_incentivescheme_payout_frequency'),
        ('targets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('finalizing', 'Finalizing'), ('computing', 'Computing'), ('under_review', 'Under review'), ('approved', 'Approved'), ('disbursed', 'Disbursed'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('readiness', models.JSONField(blank=True, default=dict)),
                ('readiness_overridden', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True, default='')),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('achievement_computation_id', models.BigIntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('register_ref', models.CharField(blank=True, default='', max_length=100)),
                ('total_payout', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ],
            options={
                'db_table': 'incentives_payoutcycle',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='payoutrun',
            name='inc_run_live_uniq',
        ),
        migrations.AddField(
            model_name='payoutrun',
            name='kind',
            field=models.CharField(choices=[('estimate', 'Estimate'), ('final', 'Final'), ('adjustment', 'Adjustment')], db_index=True, default='final', max_length=15),
        ),
        migrations.AddField(
            model_name='payoutrun',
            name='reference_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='incentives.payoutrun'),
        ),
        migrations.AddField(
            model_name='payoutcycle',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payoutcycle',
            name='disbursed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payoutcycle',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payoutcycle',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payoutcycle',
            name='target_period',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payout_cycle', to='targets.targetperiod'),
        ),
        migrations.AddField(
            model_name='payoutrun',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='incentives.payoutcycle'),
        ),
        migrations.AddIndex(
            model_name='payoutrun',
            index=models.Index(fields=['cycle', 'kind'], name='inc_run_cycle_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='payoutrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['superseded', 'failed']), _negated=True), fields=('scheme', 'target_period', 'kind'), name='inc_run_live_uniq'),
        ),
        migrations.AddIndex(
            model_name='payoutcycle',
            index=models.Index(fields=['status'], name='inc_cycle_status_idx'),
        ),
    ]
