# Generated by Django 5.2 on 2026-07-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0005_payoutcycle_remove_payoutrun_inc_run_live_uniq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='hold_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='payout',
            name='hold_status',
            field=models.CharField(choices=[('none', 'Not held'), ('held', 'Held'), ('released', 'Released')], db_index=True, default='none', max_length=10),
        ),
    ]
