# Generated by Django 5.2 on 2026-07-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0006_payout_hold_reason_payout_hold_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='adjustment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
